[package]
name = "git-future"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "An async-first library for reading git repositories"
keywords = ["async", "git"]
categories = ["no-std", "development-tools"]
readme = "README.md"
repository = "https://codeberg.org/cyberia-ng/git-future"

[dependencies]
accessory = "2.1.0"
chrono = { version = "0.4.44", default-features = false, features = ["alloc"] }
hex = { version = "0.4.3", default-features = false, features = [] }
miniz_oxide = "0.9.1"
nom = { version = "8.0.0", default-features = false, features = ["alloc"] }
similar = { version = "3.1.0", default-features = false, features = ["bytes"], optional = true }

[dev-dependencies]
futures = "0.3.32"
hex-literal = "1.1.0"
rand_core = "0.10.0"
rand_pcg = "0.10.1"
rusty-hook = "0.11.2"
tempfile = "3.27.0"

[features]
default = ["diff"]
diff = ["dep:similar"]
